#!/bin/bash

set -e

function iopstest_command() {

   function _usage() {
     echo "usage: iopstest <action> <database> <test>,<test>,...<testN>"
     exit 0
   }

   function _debug() {
     echo "debug: $*"
   }

   function _error() {
     echo "error: $*" >&2
     exit 1
   }

   function _trace() {
     echo "trace: $*"
   }

   ### start ###

   for p in $*; do
      [[ $p =~ -h ]]     && _usage;
      [[ $p =~  help ]]  && _usage;
      [[ $p =~  usage ]] && _usage;
   done

   local action="$1"

   (echo "provision destroy" | grep "$action") || \
      _error "unsupported command action '$action'"

   local database="$2"

   shift
   shift
   local testIds="$*"
         testIds=${testIds//,/ }  # replace commas w/ spaces
         testIds=$(echo $testIds) # replace multiple spaces w/ one space

   source lib/libiopstest

   local t
   for t in $testIds; do
      libiopstest $action $database $t
   done

   exit 0
}

iopstest_command $*
