#!/bin/bash

set -e
set -x

function iopstest_command() {

   function _usage() {
     echo "usage: iopstest <action> <database> <test>,<test>,...<testN>"
     exit 0
   }

   function _debug() {
     echo "debug: $*"
   }

   function _error() {
     echo "error: $*" >&2
     exit 1
   }

   function _trace() {
     echo "trace: $*"
   }

   ### start ###

   local IOPSTEST_ROOT=$(pwd)
   local IOPSTEST_CONFIG=$(pwd)/conf/iopstest.conf

   if [[ ! -f $IOPSTEST_CONFIG ]]; then
      _error "file not found $IOPSTEST_CONFIG"
   fi

   for p in $*; do
      [[ $p =~ -h ]]     && _usage;
      [[ $p =~  help ]]  && _usage;
      [[ $p =~  usage ]] && _usage;
   done

   local action="$1"

   (echo "provision destroy" | grep "$action") || \
      _error "unsupported command action '$action'"

   local database="$2"

   shift
   shift
   local testIds="$*"
         testIds=${testIds//,/ }  # replace commas w/ spaces
         testIds=$(echo $testIds) # replace multiple spaces w/ one space

   source lib/libiopstest

   local t
   for t in $testIds; do

      options=$(cat $IOPSTEST_ROOT/conf/iopstest.conf | grep -v "^#" | grep "$database" | grep " $t " )

      if [[ -z $options ]]; then
         _error "test configuration not found in $iopstest_config_file"
      fi

      libiopstest $action $options
      #libiopstest $action $database $t

   done

   exit 0
}

iopstest_command $*
