variable "username" { }
variable "key_name" { }
variable "key_path" { }
variable "aws_region" { }
variable "aws_access_key" { }
variable "aws_secret_key" { }
variable "subnet_id" { }
variable "instance_type" { }
variable "instance_name" { }
variable "aws_amis" { }
variable "security_group_name" { }
variable "vpc_id" { } 
