#!/bin/bash

set -e

function libiopstest() {

   local action="$1"
   local database="$2"
   local testId="$3"
   local machine="$4"
   local workload="$5"

   local workspace_root="${IOPSTEST_ROOT}/.workspace"
   local workspace="${workspace_root}/${database}/${testId}"

   local wkdir
   cd $IOPSTEST_ROOT

   #
   # configure assembly components
   #

   local ASSEMBLY="common machine $machine $database ycsb"

#   if [[ ! -z $ioptest_datadog_api_key ]]; then
#      ASSEMBLY="common machine $machine $datadog $database ycsb"
#   fi

   #
   # load the environment for any action
   #

   for wkdir in $ASSEMBLY; do
      case $wkdir in
          machine)
              # load TF_ variables associated with the machine parameter
              if [[ -f specs/$wkdir/$machine.env.sh ]]; then
                 source specs/$wkdir/$machine.env.sh
              fi
              ;;
          *)
              # load TF_variables associated with component of the assembly
              if [[ -f specs/$wkdir/$wkdir.env.sh ]]; then
                 source specs/$wkdir/$wkdir.env.sh
              fi
              ;;
      esac
   done

   #
   # set runtime TF_ variable names
   #

   for wkdir in $ASSEMBLY; do
      case $wkdir in
          cassandra)
              TF_VAR_csdb_instance_name="${TF_VAR_csdb_instance_name}-${testId}"
              TF_VAR_csdb_security_group_name="${TF_VAR_csdb_security_group_name}-${testId}"
              export TF_VAR_machine_instance_name=$TF_VAR_csdb_instance_name
              export TF_VAR_machine_security_group_name=$TF_VAR_csdb_security_group_name
              ;;
          mongodb)
              TF_VAR_mgdb_instance_name="${TF_VAR_mgdb_instance_name}-${testId}"
              TF_VAR_mgdb_security_group_name="${TF_VAR_mgdb_security_group_name}-${testId}"
              export TF_VAR_machine_instance_name=$TF_VAR_mgdb_instance_name
              export TF_VAR_machine_security_group_name=$TF_VAR_mgdb_security_group_name
              ;;
          ycsb)
              TF_VAR_ycsb_security_group_name="${TF_VAR_ycsb_security_group_name}-${database}-${testId}"
              TF_VAR_ycsb_instance_name="${TF_VAR_ycsb_instance_name}-${database}-${testId}"
              TF_VAR_ycsb_desired_workload="${workload}"
              ;;
      esac
   done

   #
   # take the action
   #

   case $action in

      provision)

         if [[ -d $workspace ]]; then
            _error "found existing $workspace (hint: try 'iopstest destroy $database $testId')"
         fi

         mkdir -p $workspace/

         for wkdir in $ASSEMBLY; do

            source="terraform-${wkdir}"
            if [[ "$wkdir" == "ycsb" ]]; then
               source="terraform-YCSB"
            fi;

            if [[ "$wkdir" == "mongodb" ]]; then
               source="terraform-mongo"
            fi;

            if [[ -d $source ]]; then
               cp -R $source/* $workspace/
            fi

            # create or append to all spec tfvars into one terraform.tfvars
            if [ -f specs/$wkdir/$wkdir.auto.tfvars ]; then
               cat specs/$wkdir/$wkdir.auto.tfvars | tee -a $workspace/terraform.tfvars
            fi

            if [[ "$wkdir" == "ycsb" ]]; then
               if [[ -d specs/ycsb/workloads ]]; then
                  cp -R specs/ycsb/workloads/* $workspace/
               fi
            fi
         done

         cd $workspace/
         ls -l
         terraform init
         terraform get
         terraform plan
         terraform apply -auto-approve
         cd -
         ;;


      destroy)

         if [[ -f $workspace/terraform.tfstate ]]; then
            cd $workspace/
            terraform destroy
            cd -
         fi

         if [[ -d $workspace ]]; then
            rm -Rf $workspace
         fi

         # todo: if workspace_root is empty then remove workspace_root
         ;;


      *)
        _error "unsupported libiopstest action '$action'"
        exit 1
        ;;

   esac
}
